name: Deploy ris-portfolio to 3.143.115.172 (Common kranti Server)

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using ssh-key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_ED25519_KEY }}
        
        script: |
          cd /var/www/html/analyzen/risalatsiddique.com/front-end/
          echo "Pulling latest commit"
          git pull origin main
          echo "Install packages"
          npm install
          echo "Building app"
          npm run build
          echo "Deployment is successfull!"
